import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "./StoreProvider";


import Header from "@/components/header";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header />
          <Navbar />
          {children}

          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
